### ISSUE TITLE
Crash when loading a new world.

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Elemental-Caves#23]
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/18/14 12:58 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(ExtendedBlockStorage.java:96)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:665)
    at net.minecraft.world.World.setBlock(World.java:517)
    at sobiohazardous.mods.ec.cavetype.CaveType.generateCeiling(CaveType.java:201)
    at sobiohazardous.mods.ec.cavetype.CaveType.generate(CaveType.java:151)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.replaceCaves(ECWorldGenerator.java:78)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.generateSurface(ECWorldGenerator.java:41)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.generate(ECWorldGenerator.java:27)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:102)
    at net.minecraft.world.gen.ChunkProviderServer.populate(ChunkProviderServer.java:256)
    at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1162)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:150)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:307)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:79)
    at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:96)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:746)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 909048480 bytes (866 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP v9.03 FML v7.2.196.1082 Minecraft Forge 10.12.1.1082 5 mods loaded, 5 mods active
    mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{7.2.196.1082} [Forge Mod Loader] (forgeSrc-1.7.2-10.12.1.1082.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{10.12.1.1082} [Minecraft Forge] (forgeSrc-1.7.2-10.12.1.1082.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    examplemod{1.0} [examplemod] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ElementalCaves{1.7.2-1.0.0} [Elemental Caves] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
#@!@# Game crashed! Crash report saved to: #@!@# .\crash-reports\crash-2014-05-18_12.58.38-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by Delocuro** [comment]
Also got this one when coming out of a Nether portal.

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 5/18/14 1:31 PM
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
    at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(ExtendedBlockStorage.java:96)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:665)
    at net.minecraft.world.World.setBlock(World.java:517)
    at sobiohazardous.mods.ec.cavetype.CaveType.generateCeiling(CaveType.java:201)
    at sobiohazardous.mods.ec.cavetype.CaveType.generate(CaveType.java:151)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.replaceCaves(ECWorldGenerator.java:78)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.generateSurface(ECWorldGenerator.java:41)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.generate(ECWorldGenerator.java:27)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:102)
    at net.minecraft.world.gen.ChunkProviderServer.populate(ChunkProviderServer.java:256)
    at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1162)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:150)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:163)
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:487)
    at net.minecraft.world.World.getBlock(World.java:392)
    at net.minecraft.world.Teleporter.placeInExistingPortal(Teleporter.java:115)
    at net.minecraft.world.Teleporter.placeInPortal(Teleporter.java:42)
    at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:593)
    at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:497)
    at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:485)
    at net.minecraft.entity.player.EntityPlayerMP.travelToDimension(EntityPlayerMP.java:583)
    at net.minecraft.entity.Entity.onEntityUpdate(Entity.java:460)
    at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:248)
    at net.minecraft.entity.Entity.onUpdate(Entity.java:412)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:1775)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:342)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:341)
    at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:326)
    at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37)
    at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.processPacket(C03PacketPlayer.java:163)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:232)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:720)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:608)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:746)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(ExtendedBlockStorage.java:96)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:665)
    at net.minecraft.world.World.setBlock(World.java:517)
    at sobiohazardous.mods.ec.cavetype.CaveType.generateCeiling(CaveType.java:201)
    at sobiohazardous.mods.ec.cavetype.CaveType.generate(CaveType.java:151)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.replaceCaves(ECWorldGenerator.java:78)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.generateSurface(ECWorldGenerator.java:41)
    at sobiohazardous.mods.ec.world.gen.ECWorldGenerator.generate(ECWorldGenerator.java:27)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:102)
    at net.minecraft.world.gen.ChunkProviderServer.populate(ChunkProviderServer.java:256)
    at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1162)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:150)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:163)
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:487)

-- Requested block coordinates --
Details:
    Found chunk: true
    Location: World: (1952,255,2144), Chunk: (at 0,15,0 in 122,134; contains blocks 1952,0,2144 to 1967,255,2159), Region: (3,4; contains chunks 96,128 to 127,159, blocks 1536,0,2048 to 2047,255,2559)
Stacktrace:
    at net.minecraft.world.World.getBlock(World.java:392)
    at net.minecraft.world.Teleporter.placeInExistingPortal(Teleporter.java:115)
    at net.minecraft.world.Teleporter.placeInPortal(Teleporter.java:42)
    at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:593)
    at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:497)
    at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:485)
    at net.minecraft.entity.player.EntityPlayerMP.travelToDimension(EntityPlayerMP.java:583)
    at net.minecraft.entity.Entity.onEntityUpdate(Entity.java:460)
    at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:248)
    at net.minecraft.entity.Entity.onUpdate(Entity.java:412)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:1775)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:342)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 1928
    Entity Name: Player357
    Entity's Exact location: 2073.00, 47.85, 2262.00
    Entity's Block location: World: (2073,47,2262), Chunk: (at 9,2,6 in 129,141; contains blocks 2064,0,2256 to 2079,255,2271), Region: (4,4; contains chunks 128,128 to 159,159, blocks 2048,0,2048 to 2559,255,2559)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:341)
    at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:326)
    at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37)
    at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.processPacket(C03PacketPlayer.java:163)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:232)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@73ae9f7c
Stacktrace:
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:720)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:608)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:746)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 503029824 bytes (479 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    AABB Pool Size: 1863 (104328 bytes; 0 MB) allocated, 1287 (72072 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.03 FML v7.2.196.1082 Minecraft Forge 10.12.1.1082 5 mods loaded, 5 mods active
    mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.2.196.1082} [Forge Mod Loader] (forgeSrc-1.7.2-10.12.1.1082.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.12.1.1082} [Minecraft Forge] (forgeSrc-1.7.2-10.12.1.1082.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    examplemod{1.0} [examplemod] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ElementalCaves{1.7.2-1.0.0} [Elemental Caves] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Player357'/1928, l='New World', x=2073.00, y=47.85, z=2262.00]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
#@!@# Game crashed! Crash report saved to: #@!@# .\crash-reports\crash-2014-05-18_13.31.34-server.txt
[13:31:35] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[13:31:35] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[13:31:35] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[13:31:37] [Server thread/INFO] [FML]: Unloading dimension 0
[13:31:37] [Server thread/INFO] [FML]: Unloading dimension -1
[13:31:37] [Server thread/INFO] [FML]: Unloading dimension 1
[13:31:37] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[13:31:37] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
```
